language: ruby
cache: bundler
node_js: 
- "4.2"
rvm:
- 2.3.3

install:
  - . $HOME/.nvm/nvm.sh
  - nvm install stable
  - nvm use stable
  - npm install

before_script:
 - chmod +x ./scripts/cibuild 
 
script: ./scripts/cibuild

env:
  global:
  - NOKOGIRI_USE_SYSTEM_LIBRARIES=true 

sudo: false