language: ruby
dist: trusty
cache: bundler
node_js: 
- "4.2"
rvm:
- 2.3.3

addons:
  apt:
    packages:
      - google-chrome-stable

install:
  - . $HOME/.nvm/nvm.sh
  - nvm install stable
  - nvm use stable
  - npm install

before_script:
 - chmod +x ./scripts/cibuild 
 - export DISPLAY=:99.0
 - sh -e /etc/init.d/xvfb start &
 - sleep 3
 
script: ./scripts/cibuild

env:
  global:
  - NOKOGIRI_USE_SYSTEM_LIBRARIES=true 

sudo: false